name: Build and Bundle Query Search

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget dpkg-dev gcc g++ make cmake zip

    - name: Download and Extract usearch deb package
      run: |
        wget https://github.com/unum-cloud/usearch/releases/download/v2.17.7/usearch_linux_amd64_2.17.7.deb
        mkdir extracted
        dpkg-deb -x usearch_linux_amd64_2.17.7.deb extracted

    - name: Prepare headers
      run: |
        mkdir -p usearch/golang
        cp extracted/usr/local/include/usearch.h usearch/golang/

    - name: Tidy go.mod
      env:
        CGO_CFLAGS: "-I${{ github.workspace }}/extracted/usr/local/include"
        CGO_LDFLAGS: "-L${{ github.workspace }}/extracted/usr/local/lib -lusearch_c"
      run: |
        go mod tidy

    - name: Build query_search binary
      env:
        CGO_CFLAGS: "-I${{ github.workspace }}/extracted/usr/local/include"
        CGO_LDFLAGS: "-L${{ github.workspace }}/extracted/usr/local/lib -lusearch_c"
      run: |
        go build -o query_search ./cmd/main.go

    - name: Bundle query_search and libusearch_c.so into ZIP
      run: |
        mkdir bundle
        cp query_search bundle/
        cp extracted/usr/local/lib/libusearch_c.so bundle/
        cd bundle
        zip ../query_search_linux.zip query_search libusearch_c.so

    - name: Upload bundled zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: query_search_linux
        path: query_search_linux.zip
