name: Build Static Query Search (with local usearch bindings)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++ make wget

    - name: Clone usearch C++ source
      run: |
        git clone --recurse-submodules https://github.com/unum-cloud/usearch.git

    - name: Clone usearch golang bindings
      run: |
        mkdir -p usearch/bindings
        git clone https://github.com/unum-cloud/usearch-golang.git usearch/bindings/golang

    - name: Build static libusearch_c.a
      run: |
        cd usearch
        cmake -B build -DUSEARCH_BUILD_SHARED=OFF -DUSEARCH_BUILD_STATIC=ON .
        cmake --build build

    - name: Add replace directive for local usearch golang binding
      run: |
        go mod edit -replace=github.com/unum-cloud/usearch/golang=./usearch/bindings/golang

    - name: Build query_search binary
      env:
        CGO_CFLAGS: "-I${{ github.workspace }}/usearch/include"
        CGO_LDFLAGS: "-L${{ github.workspace }}/usearch/build -l:libusearch_c.a -static"
      run: |
        go mod tidy
        go build -o query_search ./cmd/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: query_search_binary
        path: query_search
