name: Build Go App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install usearch native library
      run: |
        wget https://github.com/unum-cloud/usearch/releases/latest/download/usearch-ubuntu22-x86_64.deb
        sudo dpkg -i usearch-ubuntu22-x86_64.deb

    - name: Build the binary
      run: |
        go mod tidy
        make build