name: Build Go App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'  # your Go version

    - name: Build the binary
      run: |
        go mod tidy
        make build

    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: query_search_binary
        path: query_search
